### ISSUE TITLE
DTS.DTT.Preterm について関数適用のパーズを切替可能にする

### ISSUE THREAD

**Issue by hinarid** [DaisukeBekki/lightblue#24]
DTS.DTT.Preterm について、表示の方法として `loves(john,mary)` と `loves(mary)(john)` を切り替えられるようにしたいです。
現時点では Preterm の表示として Show を使っていますが、新しく関数を実装する必要があります。

**Comment by DaisukeBekki** [comment]
useWaniブランチ内で、

DTS.UDTTdeBruijn.toText' :: Bool -> (Preterm a) -> T.Text
DTS.UDTTvarName.toText' :: Bool -> (Preterm a) -> T.Text

を定義してexportしました。第一引数がTrueだとf(y)(x)がf(x,y)になり、Falseだとそのままです。toTeXやtoMathMLバージョンはのちほど。
