### ISSUE TITLE
DTS.Prover.Wani.Backward モジュールの未定義規則

### ISSUE THREAD

**Issue by DaisukeBekki** [DaisukeBekki/lightblue#56]
最新のmaster branch (bf2666da1814e85a4c4aa00455d9f1ddd1f1ed70)で、jsemの読み込み＆推論に挑戦してみましたが、Waniでエラーが出ました。コマンドは、以下の通り（~/program/jsem は、僕のローカル環境でのJSeMリポジトリの場所）です。

```shell
stack run lightblue -- jsem -s text -f ~/program/jsem/data/v1.0/GeneralizedQuantifier.xml -m juman
``` 

出力は以下の通りです。一行目はトライしたProof search queryで、その下がエラーです。

```shell
s0:(u0:(u1:entity)✕(u2:entity)✕(イタリア~人(u2,u1)))✕(u4:entity)✕(u5:成る/なる(u4,π1(u0),λx0.(u6:(u7:entity)✕( 世界最高/せかいさいこう(u7,x0)))✕(u9:entity)✕(テノール~歌手(u9,x0))))✕(＃タ(u4)) |- ?:((u13:entity)✕(u14:(u15:entity)✕(世界最高/せかいさいこう(u15,u13)))✕(u17:(u18:entity)✕(u19:成る/なる(u18,u13,λx1.(u20:entity)✕(テノール~歌手(u20,x1))))✕(＃タ(u18)))✕(u23:entity)✕(イタリア~人(u23,u13)))
lightblue: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at src/DTS/Prover/Wani/Backward.hs:459:36 in lightblue-0.3.3-BpTZ4ABQbpWDth5GUnKnmZ:DTS.Prover.Wani.Backward
``` 

エラーは、以下の場所で、おそらくEFQが未定義になっている、という意味かと思いました。

[https://github.com/DaisukeBekki/lightblue/blob/bf2666da1814e85a4c4aa00455d9f1ddd1f1ed70/src/DTS/Prover/Wani/Backward.hs#L458](https://github.com/DaisukeBekki/lightblue/blob/bf2666da1814e85a4c4aa00455d9f1ddd1f1ed70/src/DTS/Prover/Wani/Backward.hs#L458
)

上のproof search queryがそもそも解けるのかについて、パーズの問題や、必要な世界知識の問題はあるのですが、まずはWaniのエラーについてフィードバックします。

**Comment by DaisukeBekki** [comment]
以下のようなエラーも見つかりました。

```shell
------[Signature]-----------------------------------------------------------------------------------
dummy:entity, ＃場所:(x0:entity)→ (x1:entity)→ type, ＃存在:(x0:entity)→ (x1:entity)→ type, イタリア~人:(x0:entity)→ (x1:entity)→ type, ＃タ:(x0:entity)→ type, 成る/なる:(u0:(x0:entity)→ type)→ (x1:entity)→ (x2:entity)→ type, テノール~歌手:(x0:entity)→ (x1:entity)→ type, 世界最高/せかいさいこう:(x0:entity)→ (x1:entity)→ type
------[Type check query]----------------------------------------------------------------------------
s0:(u0:(x0:entity)✕(x1:entity)✕(イタリア~人(x1,x0)))✕(x2:entity)✕(u2:成る/なる(x2,π1(u0),λx3.(u3:(x4:entity)✕(世界最高/せかいさいこう(x4,x3)))✕(x5:entity)✕(テノール~歌手(x5,x3))))✕(＃タ(x2)) |- (u7:(u8:entity)✕(u9:(u10:entity)✕(u11:成る/なる(u10,u8,λx6.(u12:(u13:entity)✕(世界最高/せかいさいこう(u13,x6)))✕(u15:entity)✕(テノール~歌手(u15,x6))))✕(＃タ(u10)))✕(u18:entity)✕(イタリア~人(u18,u8)))✕(u20:entity)✕(u21:＃存在(u20,π1(u7)))✕(u22:＃場所(u20,@entity))✕(＃タ(u20)):type
lightblue: src/DTS/Prover/Wani/Forward.hs:105:29-100: Non-exhaustive patterns in Arrow xArg' xRes'
```

**Comment by hinarid** [comment]
EFQ について現時点で実装がないため、対応はするのですが、取り急ぎの回避策として DNE をご使用いただくことは可能ですか？
その場合は以下のような暫定対応が可能です。

1. インターフェイス側で Prover を呼び出す時の LogicSystem を変更する方法
https://github.com/DaisukeBekki/lightblue/blob/master/app/lightblueMain.hs#L260 で `Just QT.Intuitionistic` -> `Jus QT.Classic` と変更することを想定しています。Classic では DNE を使用します。

2. Wani 側で Intuitionistic として EFQ ではなく DNE を使用する関数を返す方法

2 番は嘘になるので、できれば 1 番がいいのですが、その場合他の Prover にも影響が出てしまうのでご意見をいただきたいです。

**Comment by DaisukeBekki** [comment]
> EFQ について現時点で実装がないため、対応はするのですが、取り急ぎの回避策として DNE をご使用いただくことは可能ですか？

調査＆対応有り難うございます。当面、1.の方法でこのバグを回避します。

> 1. インターフェイス側で Prover を呼び出す時の LogicSystem を変更する方法
>    https://github.com/DaisukeBekki/lightblue/blob/master/app/lightblueMain.hs#L260 で `Just QT.Intuitionistic` -> `Just QT.Classical` と変更することを想定しています。Classical では DNE を使用します。

これはゆくゆくはIntuitionisticに戻したいですが、その理由は、DTSではanaphora resolutionでDNEが使えないことを、以下のような（Kampが論じているような）anaphoric potentialの違いの根拠としているからです。

A boy did not show up this morning.  He was asleep.
Not every boy showed up this morning.  *He was asleep.

**Comment by DaisukeBekki** [comment]
@hinarid exhaustiveではないpattern matchが現れるのは以下の3箇所なので、これを場合分けすれば解消しそうにみえます（が、pattern matchに失敗した場合はどういうtermにすべきなのか……）。

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L105

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L154

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L155

**Comment by hinarid** [comment]
EFQ を実装しました。挙動を確認したのちプルリクエストを作成します。

**Comment by DaisukeBekki** [comment]
> EFQ を実装しました

おお、すごい。これがうまくいけばlogicalSystemをIntuitionisticに戻せますね。

**Comment by hinarid** [comment]
gem の証明に成功し、pars の証明に失敗することを確認できたので、一応動きそうということでプルリクエストを作成します。
これに伴って、[waniTest](https://github.com/hinarid/waniTest) も更新しました。
