### ISSUE TITLE
Non-exhaustive patterns エラー

### ISSUE THREAD

**Issue by hinarid** [DaisukeBekki/lightblue#60]
[bf2666d](https://github.com/DaisukeBekki/lightblue/commit/bf2666da1814e85a4c4aa00455d9f1ddd1f1ed70)におけるエラー

```
------[Signature]-----------------------------------------------------------------------------------
dummy:entity, ＃場所:(x0:entity)→ (x1:entity)→ type, ＃存在:(x0:entity)→ (x1:entity)→ type, イタリア~人:(x0:entity)→ (x1:entity)→ type, ＃タ:(x0:entity)→ type, 成る/なる:(u0:(x0:entity)→ type)→ (x1:entity)→ (x2:entity)→ type, テノール~歌手:(x0:entity)→ (x1:entity)→ type, 世界最高/せかいさいこう:(x0:entity)→ (x1:entity)→ type
------[Type check query]----------------------------------------------------------------------------
s0:(u0:(x0:entity)✕(x1:entity)✕(イタリア~人(x1,x0)))✕(x2:entity)✕(u2:成る/なる(x2,π1(u0),λx3.(u3:(x4:entity)✕(世界最高/せかいさいこう(x4,x3)))✕(x5:entity)✕(テノール~歌手(x5,x3))))✕(＃タ(x2)) |- (u7:(u8:entity)✕(u9:(u10:entity)✕(u11:成る/なる(u10,u8,λx6.(u12:(u13:entity)✕(世界最高/せかいさいこう(u13,x6)))✕(u15:entity)✕(テノール~歌手(u15,x6))))✕(＃タ(u10)))✕(u18:entity)✕(イタリア~人(u18,u8)))✕(u20:entity)✕(u21:＃存在(u20,π1(u7)))✕(u22:＃場所(u20,@entity))✕(＃タ(u20)):type
lightblue: src/DTS/Prover/Wani/Forward.hs:105:29-100: Non-exhaustive patterns in Arrow xArg' xRes'
```

**Comment by DaisukeBekki** [comment]
--verbose オプションを使用すると、type check/infer の途中経過が（呼び出されるWani用のproof search queryも含めて）表示されます。

**Comment by DaisukeBekki** [comment]
@hinarid exhaustiveではないpattern matchが現れるのは以下の3箇所なので、これを場合分けすれば解消しそうにみえます（が、pattern matchに失敗した場合はどういうtermにすべきなのか……）。

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L105

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L154

https://github.com/DaisukeBekki/lightblue/blob/48cbdf02e655986c85d6ca769c6436c1c1db678e/src/DTS/Prover/Wani/Forward.hs#L155

**Comment by hinarid** [comment]
あまり分析はしていませんが、Forward l105 を変更したところ動くようにはなりました。
あまり分析をしていないのでまだpush はしませんが、ご参考になりうると思いましたので取り急ぎ誤共有いたします。

```
                    case pair of
                      [A.Arrow fArg fRes,A.Arrow xArg xRes] -> 
                        let (xArg',xRes') = 
                              case A.shiftIndices (A.Arrow xArg xRes) (length fArg) 0 of
                                A.Arrow a b -> (a,b)
                                c -> ([],c)
                            arg = xArg' ++ fArg
```

**Comment by hinarid** [comment]
@DaisukeBekki 
[bugFix60](https://github.com/DaisukeBekki/lightblue/tree/bugFix60) ブランチを作成し、push しました。
その後の挙動が正しいかについて確認できていない段階で恐縮ですがお役立てください。

**Comment by hinarid** [comment]
Arrowterm での shiftIndices の、インデックスの変更のついでに正規化を行うという仕様に由来したエラーでした。

shiftIndices はすでに多く使用されており、shitIndices 側の仕様を変えるのは影響が大きいと感じました。
https://github.com/DaisukeBekki/lightblue/blob/bugFix60/src/DTS/Prover/Wani/Forward.hs#L158 にあわせ、Forward 内での shiftIndices の使い方を変える方向で対応しました。

以下の commit の内容をもとに merge を行い、pull リクエストを投げたいと思います。
[21b978a](https://github.com/DaisukeBekki/lightblue/commit/21b978a2eaccc191ae879b5e26b160c7c0fe7215)
