### ISSUE TITLE
wani の prove について、深さを下から増やしていくオプションを追加する

### ISSUE THREAD

**Issue by hinarid** [DaisukeBekki/lightblue#62]

**Comment by hinarid** [comment]
`searchProofWithIncrementalDepth` という関数を用意しました。
当初深さについて無限のリストでインクリメントするというお話でしたが、それだと Unknown のときに証明が終わらなくなってしまうので、とりあえず ProofSearchQuery で maxDepth として指定した値までのインクリメントを繰り返す形としました。
maxDepth が -1 の場合は証明項が得られるまで証明を繰り返すため、計算が終わらないことがあります。

**Comment by DaisukeBekki** [comment]
> ProofSearchQuery で maxDepth として指定した値までのインクリメントを繰り返す形としました

なかなか素晴らしいupdateになったと思います。その後、コマンドラインのglobal optionからmaxDepthを指定できるようにしました。
