### ISSUE TITLE
＃モラウ、#アゲルのsignatureの修正

### ISSUE THREAD

**Issue by mainzel131** [DaisukeBekki/lightblue#71]
https://github.com/DaisukeBekki/lightblue/blob/1cac924db38ef587be516a47f17f1bff3db84540/src/Parser/Language/Japanese/MyLexicon.hs#L596

signatureの修正

**Comment by DaisukeBekki** [comment]
@mainzel131 morau branchに「貰う」の語彙項目案をpushしました。
これでうまくいくようなら、「あげる」や「いただく」も同様にupdateします。
